<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit83cdec2b1edbde1a9f0c8d5044a00bb1
{
    public static $prefixLengthsPsr4 = array (
        'S' => 
        array (
            'Symfony\\Component\\EventDispatcher\\' => 34,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Symfony\\Component\\EventDispatcher\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/event-dispatcher',
        ),
    );

    public static $prefixesPsr0 = array (
        'G' => 
        array (
            'Guzzle\\Tests' => 
            array (
                0 => __DIR__ . '/..' . '/guzzle/guzzle/tests',
            ),
            'Guzzle' => 
            array (
                0 => __DIR__ . '/..' . '/guzzle/guzzle/src',
            ),
        ),
        'A' => 
        array (
            'Aws' => 
            array (
                0 => __DIR__ . '/..' . '/aws/aws-sdk-php/src',
            ),
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit83cdec2b1edbde1a9f0c8d5044a00bb1::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit83cdec2b1edbde1a9f0c8d5044a00bb1::$prefixDirsPsr4;
            $loader->prefixesPsr0 = ComposerStaticInit83cdec2b1edbde1a9f0c8d5044a00bb1::$prefixesPsr0;

        }, null, ClassLoader::class);
    }
}
